language: c
dist: bionic
compiler:
  - gcc
git:
  depth: 3
  
before_install:
  - sudo add-apt-repository universe
  - sudo apt-get update
  - sudo apt-get install -y libffi-dev gir1.2-glib-2.0 libgirepository1.0-dev
    libtool texinfo autoconf automake gnulib git
    texlive-base texlive-generic-recommended texlive-latex-base
  - sudo apt-get install -y guile-2.2-dev

script:
  - echo "hello?"

env:
  - GUILE_BUILD=pkg22
  global:
    - GUILD=/usr/bin/guild
    - LANG=C.UTF-8
    - TERM=dumb
    - VERBOSE=true
