language: c
dist: bionic
compiler:
  - gcc
git:
  depth: 2
  
before_install:
  - sudo add-apt-repository universe
  - sudo apt-get update
  - sudo apt-get install -y libffi-dev gir1.2-glib-2.0 libgirepository1.0-dev
    libtool texinfo autoconf automake gnulib git
    texlive-base texlive-generic-recommended texlive-latex-base
  - if [ $GUILE_BUILD == pkg22 ]; then sudo apt-get install -y guile-2.2-dev; fi
  - if [ $GUILE_BUILD == pkg30 ]; then sudo apt-get install -y guile-3.0-dev; fi
  - if [ $GUILE_BUILD == stable22 ]; then sudo apt-get install -y libunistring-dev libgmp-dev libffi-dev; fi
  - if [ $GUILE_BUILD == master ]; then sudo apt-get install -y libunistring-dev libgmp-dev libffi-dev; fi
  - ./tools/ci_prep.sh $GUILE_BUILD

script:
  - if [ -f guile_build.txt ]; then
      ./bootstrap
      && ./configure --enable-hardening --with-gnu-filesystem-hierarchy
      && make -j4 distcheck;
    else
      echo "No guile built!" && exit 1;
    fi

env:
  matrix:
    - GUILE_BUILD=pkg22
    - GUILE_BUILD=stable22
    - GUILE_BUILD=master
  global:
    - GUILD=/usr/bin/guild
    - LANG=C.UTF-8
    - TERM=dumb
    - VERBOSE=true
